package UTS;

import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;


public class KeuanganPribadiForm extends javax.swing.JFrame {


    
    public KeuanganPribadiForm() {
        initComponents();
        
        hapusBT.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        hapusBTActionPerformed(evt);
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dapatTF = new javax.swing.JTextField();
        butuhTF = new javax.swing.JTextField();
        tabungTF = new javax.swing.JTextField();
        bebanTF = new javax.swing.JTextField();
        tanggalTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tambahBT = new javax.swing.JButton();
        hapusBT = new javax.swing.JButton();
        editBT = new javax.swing.JButton();
        simpanBT = new javax.swing.JButton();
        resetBT = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel5.setBackground(new java.awt.Color(51, 255, 51));
        jLabel5.setFont(new java.awt.Font("Juice ITC", 3, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Kebutuhan");
        jLabel5.setToolTipText("");

        dapatTF.setActionCommand("<Not Set>");

        tabungTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabungTFActionPerformed(evt);
            }
        });

        tanggalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalTFActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 255, 51));
        jLabel2.setFont(new java.awt.Font("Juice ITC", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Pendapatan");
        jLabel2.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(51, 255, 51));
        jLabel3.setFont(new java.awt.Font("Juice ITC", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Tabungan");
        jLabel3.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(51, 255, 51));
        jLabel4.setFont(new java.awt.Font("Juice ITC", 3, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Beban");
        jLabel4.setToolTipText("");

        jLabel6.setBackground(new java.awt.Color(51, 255, 51));
        jLabel6.setFont(new java.awt.Font("Juice ITC", 3, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Tanggal");
        jLabel6.setToolTipText("");

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pendapatan", "Kebutuhan", "Tabunngan", "Beban", "Tanggal"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        tambahBT.setBackground(new java.awt.Color(51, 51, 51));
        tambahBT.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        tambahBT.setForeground(new java.awt.Color(255, 255, 255));
        tambahBT.setText("Tambah");
        tambahBT.setBorderPainted(false);
        tambahBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBTActionPerformed(evt);
            }
        });

        hapusBT.setBackground(new java.awt.Color(51, 51, 51));
        hapusBT.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        hapusBT.setForeground(new java.awt.Color(255, 255, 255));
        hapusBT.setText("Hapus");
        hapusBT.setBorderPainted(false);
        hapusBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBTActionPerformed(evt);
            }
        });

        editBT.setBackground(new java.awt.Color(51, 51, 51));
        editBT.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        editBT.setForeground(new java.awt.Color(255, 255, 255));
        editBT.setText("Edit");
        editBT.setBorderPainted(false);
        editBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTActionPerformed(evt);
            }
        });

        simpanBT.setBackground(new java.awt.Color(51, 51, 51));
        simpanBT.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        simpanBT.setForeground(new java.awt.Color(255, 255, 255));
        simpanBT.setText("Simpan");
        simpanBT.setBorderPainted(false);
        simpanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBTActionPerformed(evt);
            }
        });

        resetBT.setBackground(new java.awt.Color(51, 51, 51));
        resetBT.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        resetBT.setForeground(new java.awt.Color(255, 255, 255));
        resetBT.setText("Reset");
        resetBT.setBorderPainted(false);
        resetBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bebanTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabungTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butuhTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dapatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tambahBT)
                .addGap(18, 18, 18)
                .addComponent(hapusBT)
                .addGap(18, 18, 18)
                .addComponent(editBT)
                .addGap(18, 18, 18)
                .addComponent(simpanBT)
                .addGap(18, 18, 18)
                .addComponent(resetBT)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dapatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butuhTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tabungTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bebanTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tanggalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBT)
                    .addComponent(hapusBT)
                    .addComponent(editBT)
                    .addComponent(simpanBT)
                    .addComponent(resetBT))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jurnal Keuangan Pribadi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabungTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabungTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabungTFActionPerformed

    private void tambahBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBTActionPerformed
        // Get values from text fields
        String pendapatan = dapatTF.getText();
        String kebutuhan = butuhTF.getText();
        String tabungan = tabungTF.getText();
        String beban = bebanTF.getText();
        String tanggal = tanggalTF.getText();
        // You might need to convert the date to a suitable format based on your requirements

        // Add the values to the table model
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{pendapatan, kebutuhan, tabungan, beban, tanggal});

        // Clear the text fields after adding to the table
        clearTextFields();
    }//GEN-LAST:event_tambahBTActionPerformed

    private void hapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBTActionPerformed
            // Mendapatkan baris yang dipilih
            int selectedRow = jTable1.getSelectedRow();

    // Memastikan bahwa baris yang dipilih valid
            if (selectedRow == -1) {
        // Jika tidak ada baris yang dipilih, beri peringatan atau tindakan lain sesuai kebutuhan
        // Contoh: JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            } else {
        // Hapus baris terpilih dari model tabel
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(selectedRow);
    }
    }//GEN-LAST:event_hapusBTActionPerformed

    private void resetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTActionPerformed
    dapatTF.setText("");
    butuhTF.setText("");
    tabungTF.setText("");
    bebanTF.setText("");
    tanggalTF.setText("");
    }//GEN-LAST:event_resetBTActionPerformed

    private void simpanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBTActionPerformed
            // Mendapatkan model tabel
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Memeriksa apakah ada data di tabel
    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Tidak ada data untuk disimpan.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Memilih file untuk menyimpan data
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Simpan Data");
    int userSelection = fileChooser.showSaveDialog(this);

    // Jika pengguna memilih file
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        try {
            // Mendapatkan file yang dipilih
            File fileToSave = fileChooser.getSelectedFile();

            // Membuat objek FileWriter
            FileWriter writer = new FileWriter(fileToSave);

            // Menulis header ke file
            for (int i = 0; i < model.getColumnCount(); i++) {
                writer.write(model.getColumnName(i) + "\t");
            }
            writer.write("\n");

            // Menulis data ke file
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    writer.write(model.getValueAt(i, j).toString() + "\t");
                }
                writer.write("\n");
            }

            // Menutup FileWriter
            writer.close();

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    }//GEN-LAST:event_simpanBTActionPerformed

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
            // Mendapatkan baris yang dipilih
    int selectedRow = jTable1.getSelectedRow();

    // Memastikan bahwa baris yang dipilih valid
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang akan diedit", "Peringatan", JOptionPane.WARNING_MESSAGE);
    } else {
        // Mendapatkan model tabel
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Mengisi JTextField dengan nilai dari baris yang dipilih
        dapatTF.setText(model.getValueAt(selectedRow, 0).toString());
        butuhTF.setText(model.getValueAt(selectedRow, 1).toString());
        tabungTF.setText(model.getValueAt(selectedRow, 2).toString());
        bebanTF.setText(model.getValueAt(selectedRow, 3).toString());
        tanggalTF.setText(model.getValueAt(selectedRow, 4).toString());

        // Menetapkan JTextField ke modus edit
        enableEditMode(true);

        // Dapat menetapkan aksi tombol simpan untuk menyimpan perubahan
        simpanBT.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Menetapkan nilai yang diedit ke model tabel
                model.setValueAt(dapatTF.getText(), selectedRow, 0);
                model.setValueAt(butuhTF.getText(), selectedRow, 1);
                model.setValueAt(tabungTF.getText(), selectedRow, 2);
                model.setValueAt(bebanTF.getText(), selectedRow, 3);
                model.setValueAt(tanggalTF.getText(), selectedRow, 4);

                // Mengatur JTextField ke modus non-edit
                enableEditMode(false);

                // Menghapus aksi dari tombol simpan
                simpanBT.removeActionListener(this);
            }
        });
    }
    }//GEN-LAST:event_editBTActionPerformed

    private void tanggalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalTFActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bebanTF;
    private javax.swing.JTextField butuhTF;
    private javax.swing.JTextField dapatTF;
    private javax.swing.JButton editBT;
    private javax.swing.JButton hapusBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton resetBT;
    private javax.swing.JButton simpanBT;
    private javax.swing.JTextField tabungTF;
    private javax.swing.JButton tambahBT;
    private javax.swing.JTextField tanggalTF;
    // End of variables declaration//GEN-END:variables

    private void clearTextFields() {
    dapatTF.setText("");
    butuhTF.setText("");
    tabungTF.setText("");
    bebanTF.setText("");
    tanggalTF.setText("");
    }
    
    private void enableEditMode(boolean enable) {
    tambahBT.setEnabled(!enable);
    hapusBT.setEnabled(!enable);
    resetBT.setEnabled(!enable);
    editBT.setEnabled(!enable);
    simpanBT.setEnabled(enable);

    // Menetapkan JTextField ke modus non-edit saat menonaktifkan modus edit
    dapatTF.setEditable(enable);
    butuhTF.setEditable(enable);
    tabungTF.setEditable(enable);
    bebanTF.setEditable(enable);
    tanggalTF.setEditable(enable);
}
    
}
